[package]
name = "me"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
yew = "^0.19"
wasm-bindgen = "^0.2"
wee_alloc = "^0.4.4"

[profile.dev]
opt-level = "z"
# lto is "thin-local" by def

[profile.release]
opt-level = "z"
lto = "thin"
